path:
  front_path: 'C:/Users/User/Dropbox/data/final_data/front_data/'
  furniture_path: 'C:/Users/User/Dropbox/data/final_data/furniture_data/'
  scene_info_path: 'C:/Users/User/Dropbox/data/final_data/scene_info/'
  model_info_path: 'C:/Users/User/Dropbox/data/final_data/model_info.json'
  model_info_modi_path: 'C:/Users/User/Dropbox/data/final_data/model_info_modi.json'

