_ATTR_STYLE = [
    {'id': 0, 'category': 'Modern',},
    {'id': 1, 'category': 'Chinoiserie',},
    {'id': 2, 'category': 'Kids',},
    {'id': 3, 'category': 'European',},
    {'id': 4, 'category': 'Japanese',},
    {'id': 5, 'category': 'Southeast Asia',},
    {'id': 6, 'category': 'Industrial',},
    {'id': 7, 'category': 'American Country',},
    {'id': 8, 'category': 'Vintage/Retro',},
    {'id': 9, 'category': 'Light Luxury',},
    {'id': 10, 'category': 'Mediterranean',},
    {'id': 11, 'category': 'Korean',},
    {'id': 12, 'category': 'New Chinese',},
    {'id': 13, 'category': 'Nordic',},
    {'id': 14, 'category': 'European Classic',},
    {'id': 15, 'category': 'Others',},
    {'id': 16, 'category': 'Ming Qing',},
    {'id': 17, 'category': 'Neoclassical',},
    {'id': 18, 'category': 'Minimalist',},
]

_ATTR_MATERIAL = [
    {'id': 0, 'category': 'Composition',},
    {'id': 1, 'category': 'Cloth',},
    {'id': 2, 'category': 'Leather',},
    {'id': 3, 'category': 'Glass',},
    {'id': 4, 'category': 'Metal',},
    {'id': 5, 'category': 'Solid Wood',},
    {'id': 6, 'category': 'Stone',},
    {'id': 7, 'category': 'Plywood',},
    {'id': 8, 'category': 'Others',},
    {'id': 9, 'category': 'Suede',},
    {'id': 10, 'category': 'Bamboo Rattan',},
    {'id': 11, 'category': 'Rough Cloth',},
    {'id': 12, 'category': 'Wood',},
    {'id': 13, 'category': 'Composite Board',},
    {'id': 14, 'category': 'Marble',},
    {'id': 15, 'category': 'Smooth Leather',},
]

_ATTR_THEME = [
    {'id': 0, 'category': 'Smooth Net',},
    {'id': 1, 'category': 'Lines',},
    {'id': 2, 'category': 'Wrought Iron',},
    {'id': 3, 'category': 'Cartoon',},
    {'id': 4, 'category': 'Granite Texture',},
    {'id': 5, 'category': 'Floral',},
    {'id': 6, 'category': 'Inlay Gold Carve',},
    {'id': 7, 'category': 'Texture Mark',},
    {'id': 8, 'category': 'Striped Grid',},
    {'id': 9, 'category': 'Chinese Pattern',},
    {'id': 10, 'category': 'Gold Foil',},
    {'id': 11, 'category': 'Rivet',},
    {'id': 12, 'category': 'Soft Case',},
    {'id': 13, 'category': 'Wooden Vertical Texture',},
    {'id': 14, 'category': 'Graffiti Ink Stain',},
    {'id': 15, 'category': 'Linen Texture',},
]

_SUPER_CATEGORIES_3D = [
    {'id': 1, 'category': 'Cabinet/Shelf/Desk'},
    {'id': 2, 'category': 'Bed'},
    {'id': 3, 'category': 'Chair'},
    {'id': 4, 'category': 'Table'},
    {'id': 5, 'category': 'Sofa'},
    {'id': 6, 'category': 'Pier/Stool'},
    {'id': 7, 'category': 'Lighting'},
    {'id': 8,'category': 'Aircleaner'},
    {'id': 9,'category': 'Notebook'},
    {'id': 10, 'category': 'TV'},
    {'id': 11, 'category': 'Board'},
    {'id': 12, 'category': 'Other'}
]

_CATEGORIES_3D = [
    {'id': 1, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Children Cabinet'},
    {'id': 2, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Nightstand'},
    {'id': 3, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Bookcase / jewelry Armoire'},
    {'id': 4, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Wardrobe'},
    {'id': 5, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Coffee Table'},
    {'id': 6, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Corner/Side Table'},
    {'id': 7, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Sideboard / Side Cabinet / Console Table'},
    {'id': 8, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Wine Cabinet'},
    {'id': 9, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'TV Stand'},
    {'id': 10, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Drawer Chest / Corner cabinet'},
    {'id': 11, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Shelf'},
    {'id': 12, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Round End Table'},
    {'id': 13, 'super-category': 'Bed', 'category': 'King-size Bed'},
    {'id': 14, 'super-category': 'Bed', 'category': 'Bunk Bed'},
    {'id': 15, 'super-category': 'Bed', 'category': 'Bed Frame'},
    {'id': 16, 'super-category': 'Bed', 'category': 'Single bed'},
    {'id': 17, 'super-category': 'Bed', 'category': 'Kids Bed'},
    {'id': 18, 'super-category': 'Chair', 'category': 'Dining Chair'},
    {'id': 19, 'super-category': 'Chair', 'category': 'Lounge Chair / Cafe Chair / Office Chair'},
    {'id': 20, 'super-category': 'Chair', 'category': 'Dressing Chair'},
    {'id': 21, 'super-category': 'Chair', 'category': 'Classic Chinese Chair'},
    {'id': 22, 'super-category': 'Chair', 'category': 'Barstool'},
    {'id': 23, 'super-category': 'Table', 'category': 'Dressing Table'},
    {'id': 24, 'super-category': 'Table', 'category': 'Dining Table'},
    {'id': 25, 'super-category': 'Table', 'category': 'Desk'},
    {'id': 26, 'super-category': 'Sofa', 'category': 'Three-Seat / Multi-seat Sofa'},
    {'id': 27, 'super-category': 'Sofa', 'category': 'armchair'},
    {'id': 28, 'super-category': 'Sofa', 'category': 'Loveseat Sofa'},
    {'id': 29, 'super-category': 'Sofa', 'category': 'L-shaped Sofa'},
    {'id': 30, 'super-category': 'Sofa', 'category': 'Lazy Sofa'},
    {'id': 31, 'super-category': 'Sofa', 'category': 'Chaise Longue Sofa'},
    {'id': 32, 'super-category': 'Pier/Stool', 'category': 'Footstool / Sofastool / Bed End Stool / Stool'},
    {'id': 33, 'super-category': 'Lighting', 'category': 'Pendant Lamp'},
    {'id': 34, 'super-category': 'Lighting', 'category': 'Ceiling Lamp'},

    {'id': 35, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Shoe Cabinet'},
    {'id': 36, 'super-category': 'Bed', 'category': 'Couch Bed'},
    {'id': 37, 'super-category': 'Chair', 'category': 'Hanging Chair'},
    {'id': 38, 'super-category': 'Chair', 'category': 'Folding chair'},
    {'id': 39, 'super-category': 'Table', 'category': 'Bar'},
    {'id': 40, 'super-category': 'Sofa', 'category': 'U-shaped Sofa'},
    {'id': 41, 'super-category': 'Lighting', 'category': 'Floor Lamp'},
    {'id': 42, 'super-category': 'Lighting', 'category': 'Wall Lamp'},
    {'id': 43, 'super-category': 'Aircleaner', 'category': 'Air Cleaner'},
    {'id': 44, 'super-category': 'Table', 'category': 'Wheel Table'},
    {'id': 45, 'super-category': 'Notebook', 'category': 'Notebook'},
    {'id': 46, 'super-category': 'TV', 'category': 'Stand TV'},

    {'id': 47, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Computer Desk'},
    {'id': 48, 'super-category': 'Cabinet/Shelf/Desk', 'category': 'Large Cabinet'},
    {'id': 49, 'super-category': 'Board', 'category': 'WhiteBoard'},
    {'id': 50, 'super-category': 'Other', 'category': 'Other'},
    {'id': 51, 'super-category': 'Chair', 'category': 'Deskchair'}, #from MJ (3D_data)
    {'id': 52, 'super-category': 'Computer', 'category': 'Desktop'}, #from MJ (3D_data)
    {'id': 53, 'super-category': 'Cabinet', 'category': 'Closet'}, #from MJ (3D_data)

    {'id': 54, 'super-category': 'Computer', 'category': 'Monitor'}, #from SM (3D_Blender)
    {'id': 55, 'super-category': 'Table', 'category': 'Partition Table'}, #from SM (3D_Blender)
    {'id': 56, 'super-category': 'Other', 'category': 'Partitions'}, #from MJ(3D_Data) 55->56
    {'id': 57, 'super-category': 'Other', 'category': 'Carpet'}, #from JS(blender_data) 100->57
    {'id': 58, 'super-category': 'TV wall', 'category': 'Tv Wall'} #from SM
]

_CATEGORIES_3D_TEXTURE = [
    {'id': 1, 'category': 'Flooring'},
    {'id': 2, 'category': 'Tile'},
    {'id': 3, 'category': 'Wallpaper'},
    {'id': 4, 'category': 'Stone'},
    {'id': 5, 'category': 'Paint'},
    {'id': 6, 'category': 'Wood'},
    {'id': 7, 'category': 'Cloth'},
    {'id': 8, 'category': 'Leather'},
    {'id': 9, 'category': 'Metal'},
    {'id': 10, 'category': 'Others'},
    {'id': 11, 'category': 'Marble'},
    {'id': 12, 'category': 'Outdoor floor'},
    {'id': 13, 'category': 'Mirror / Glass'},
    {'id': 14, 'category': 'Solid wood flooring'}
]